channels:
    - conda-forge
    - damianavila82
dependencies:
    - python=3
    - six
    - numpy
    - scipy
    - sympy
    - setuptools
    - cython
    - mpi4py
    - petsc4py
    - bqplot
    - ipywidgets
    - ipyparallel
    - rise
    - vtk
    - pyopengl
